### ISSUE TITLE
Add badge number

### ISSUE THREAD

**Issue by ktxc15** [MarioIannotta/MIPivotPageController#2]
Can I add badge number to icon, how to do it

**Comment by MarioIannotta** [comment]
Hi, right now it is not possible.

**Comment by MarioIannotta** [comment]
Hi, right now it's not possible.

**Comment by MarioIannotta** [comment]
Hi @ktxc15 
I just want to let you know that with the last update you can easily add the badge for each page.

You will find usefull this methods of the `MIPivotRootPage` protocol
```
@objc optional var badgeValueForPivotPage: String? { get }
@objc optional var shouldHideBadgeOnPageFocus: Bool { get }
```

In order to refresh the badge you'll need the method
`refreshBadge(forRootPageAtIndex miPivotRootPageIndex: Int) ` of `MIPivotPageController`

Have a nice day,
Mario.
